version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - mvn clean package
      - echo Building the docker image
      - docker build -t authservice-container .
      - docker tag authservice-container 860061945305.dkr.ecr.us-east-1.amazonaws.com/pension-050:authservice-container
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(docker images)
      - docker push 860061945305.dkr.ecr.us-east-1.amazonaws.com/pension-050:authservice-container
      - echo Writing definition files
      - printf '[{"name":"authservice-container","imageUri":"%s"}]' 860061945305.dkr.ecr.us-east-1.amazonaws.com/pension-050:authservice-container > taskdefinition.json

artifacts:
  files: taskdefinition.json


